name: Contributing A Plugin
description: Contributing support for a new plugin.
title: "plugin: "
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Did you read the Contributing guide?
      description: Make sure you have read the Contributing guide
      options:
        - label: I have read the Contributing guide
          required: true
  - type: input
    attributes:
      label: "Link"
      description: "Privide a link to the plugin you are working on adding support for!"
    validations:
      required: true
  - type: textarea
    validations:
      required: false
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
